import express from 'express';
import cors from 'cors';
import nodemailer from 'nodemailer';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

// Load environment variables
dotenv.config();

const app = express();
const PORT = process.env.PORT || 5000;

// Resolve static build path
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const frontendBuildPath = path.join(__dirname, '../frontend/dist');

// Middleware
app.use(cors());
app.use(express.json());

// API route for Contact Form submission
app.post('/api/contact', async (req, res) => {
  const { name, email, message } = req.body;

  if (!name || !email || !message) {
    return res.status(400).json({ error: 'All fields (name, email, message) are required.' });
  }

  // Check if SMTP variables are set up
  if (!process.env.SMTP_USER || !process.env.SMTP_PASS) {
    console.warn('WARNING: SMTP credentials not set. Email not sent. Environment variables SMTP_USER and SMTP_PASS are required.');
    // Return a mock success response so the site functions during local testing/dev
    return res.status(200).json({ 
      success: true, 
      warning: 'SMTP credentials not configured. Form received but email not sent.',
      data: { name, email, message }
    });
  }

  try {
    // Configure nodemailer transporter
    const transporter = nodemailer.createTransport({
      service: process.env.SMTP_SERVICE || 'gmail',
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS
      }
    });

    const mailOptions = {
      from: `"${name}" <${process.env.SMTP_USER}>`,
      replyTo: email, // Direct reply-to the sender
      to: 'kavychoudhary49@gmail.com', // Direct to Kavy's email address
      subject: `💼 Portfolio Project Inquiry from ${name}`,
      html: `
        <div style="font-family: Arial, sans-serif; padding: 20px; color: #333; max-width: 600px; border: 1px solid #ddd; border-radius: 8px;">
          <h2 style="color: #00d2ff; border-bottom: 2px solid #00d2ff; padding-bottom: 10px; margin-top: 0;">New Project Wave Initialized</h2>
          <p>You have received a new contact submission from your portfolio website.</p>
          
          <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
            <tr>
              <td style="padding: 8px; font-weight: bold; border-bottom: 1px solid #eee; width: 120px;">Name:</td>
              <td style="padding: 8px; border-bottom: 1px solid #eee;">${name}</td>
            </tr>
            <tr>
              <td style="padding: 8px; font-weight: bold; border-bottom: 1px solid #eee;">Email:</td>
              <td style="padding: 8px; border-bottom: 1px solid #eee;"><a href="mailto:${email}">${email}</a></td>
            </tr>
          </table>

          <div style="background: #f9f9f9; padding: 15px; border-left: 4px solid #8b5cf6; border-radius: 4px; margin-top: 20px;">
            <h4 style="margin: 0 0 10px 0; color: #8b5cf6;">Message Content:</h4>
            <p style="margin: 0; line-height: 1.5; white-space: pre-wrap;">${message}</p>
          </div>

          <p style="margin-top: 30px; font-size: 0.85rem; color: #777; border-top: 1px solid #eee; padding-top: 15px; text-align: center;">
            This email was automatically generated by your portfolio server.
          </p>
        </div>
      `
    };

    // Send the email
    await transporter.sendMail(mailOptions);
    console.log(`Email successfully sent to kavychoudhary49@gmail.com from ${email}`);
    return res.status(200).json({ success: true, message: 'Your message has been delivered directly to Kavy.' });

  } catch (error) {
    console.error('Error sending email via nodemailer:', error);
    return res.status(500).json({ error: 'Failed to send email. Please try again later or email directly.' });
  }
});

// Serve static built frontend files in production
app.use(express.static(frontendBuildPath));

// Fallback all other routes to index.html (React SPA Routing)
app.get('*', (req, res) => {
  res.sendFile(path.join(frontendBuildPath, 'index.html'));
});

// Start the server
app.listen(PORT, () => {
  console.log(`Server is running in full-stack mode on port ${PORT}`);
});
